### PR TITLE
spot the mistake!

### PR DESCRIPTION
**Pull request by Stodian**

### CODE REVIEW

**Comment by Stodian** [comment]
why did the package-lock file change?

**Comment by scruffian** [comment]
> why did the package-lock file change?

probably because you're running a different version of node/npm to me. We should update to the latest one.

**Comment by scruffian** [comment]
In Psalm 36:7 you've added "H5756" for the word refuge, but I can't see that word used in the Hebrew - where did you get it from?

**Comment by scruffian** [comment]
In Acts 16:29 I don't think the word 'jailor" is in the original, so we should use "added" instead of a strongs number.

**Comment by scruffian** [comment]
For Daniel 5:25, I think we need to do a couple of things:
1. The comma shouldn't be inside the word that is tagged with a strongs number
2. We should tag each MENE separately

**Comment by scruffian** [comment]
The strongs numbers changes in esther 1:13 don't seem to match the original text

**Comment by scruffian** [comment]
Acts 16:29 - I think the other changes in here aren't right, sorry

**Pull request closed without merging**
